//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecasIEI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biblioteca
    {
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public string codigoPostal { get; set; }
        public string longitud { get; set; }
        public string latitud { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string codMunicipal { get; set; }
    }
}
