//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecasIEI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public string codigo { get; set; }
        public string provincia1 { get; set; }
    }
}
